"""Generate the fork's Milchglas token stylesheet from the product's guarded tokens.css.

The product file defines light values on :root and dark overrides inside
@media (prefers-color-scheme: dark). This login app switches dark mode by CLASS
(tailwind darkMode "class" + next-themes), so the dark block is re-homed onto
.dark. Values pass through verbatim; nothing is invented here, which is what
keeps the login palette incapable of drifting from the product palette.
CB:decision-login-surface-realization#R-LOGSURF-03@r1 (corporate identity binds
from the first forked image).
"""
import argparse
import re
import sys
from pathlib import Path

HEADER = (
    "/* GENERATED by scripts/generate_milchglas_tokens.py from the product repo's\n"
    " * client/renderer/src/styles/tokens.css. Do not edit; regenerate instead.\n"
    " * CI regenerates against the product main branch and fails on drift. */\n"
)


def transform(source_text: str) -> str:
    root_match = re.search(r":root\s*\{([\s\S]*?)\n\}", source_text)
    if not root_match:
        sys.exit("tokens.css: no :root block found")
    dark_match = re.search(
        r"@media\s*\(prefers-color-scheme:\s*dark\)\s*\{\s*:root\s*\{([\s\S]*?)\n\s*\}\s*\n\}",
        source_text,
    )
    if not dark_match:
        sys.exit("tokens.css: no prefers-color-scheme dark :root block found")
    dark_body = re.sub(r"^    ", "  ", dark_match.group(1), flags=re.M)
    return (
        HEADER
        + ":root {"
        + root_match.group(1)
        + "\n}\n\n"
        + "/* Dark overrides re-homed from the product's media query onto the class\n"
        + "   next-themes toggles; value-identical to the source. */\n"
        + ".dark {"
        + dark_body
        + "\n}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--check", type=Path)
    args = parser.parse_args()
    generated = transform(args.source.read_text(encoding="utf-8"))
    if args.check:
        if args.check.read_text(encoding="utf-8") != generated:
            sys.exit(f"{args.check} is stale; regenerate with --out")
        print("tokens in sync")
        return
    if not args.out:
        sys.exit("one of --out or --check is required")
    args.out.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
